// Persistence feature exports

export {
  initPersistence,
  destroyPersistence,
  getGameState,
  saveGameState,
  getPageState,
  savePageState,
  saveArtifactPositions,
  getArtifactPositions,
  markArtifactCollected,
  markArtifactReturned,
  markArtifactReturnedOnPage,
  markAllArtifactsReturnedOnPage,
  getStoredInventory,
  addInventoryItem,
  removeInventoryItem,
  clearInventory,
  addTravelHistory,
  getPreviousPageUrl,
  setPreviousPageUrl,
  hasArrivedViaPortal,
  clearArrivalFlag,
  hasVisitedCurrentPage,
  clearAllGameState,
  isPersistenceAvailable,
  addVisitedRealm,
  getVisitedRealms,
  hasVisitedRealm,
  clearVisitedRealmsExceptFirst,
  getCurrentRealmUrl,
  getCurrentRealmTitle,
} from "./persistence";

export type {
  PersistenceFeatureConfig,
  StoredGameState,
  StoredInventoryItem,
  StoredPageState,
  StoredArtifactPosition,
  TravelHistoryEntry,
  VisitedRealm,
} from "./types";

